### ISSUE TITLE
The text block is all white!

### ISSUE THREAD

**Issue by SahajRana** [mallethugo/translucent-android#1]
Hey! great Work but i when i implemented it in my app it made it complete white in tht block

here's the code:

```
                 `<LinearLayout
                    android:gravity="center_vertical"
                    android:layout_width="wrap_content"
                    android:orientation="vertical"
                    android:layout_height="match_parent"
                    android:weightSum="1">
                    <com.mallethugo.translucent.TranslucentView
                        android:id="@+id/NameUSER"
                        android:textStyle="bold"
                        android:textSize="17dp"
                        android:layout_width="141dp"
                        android:layout_height="wrap_content"
                        android:fontFamily="sans-serif-condensed"
                        />`

                    <Space
                        android:layout_width="143dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="0.20"/>`

                    <TextView
                        android:visibility="visible"
                        android:id="@+id/Status"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textStyle="italic"
                        android:textSize="15dp"
                        />

                </LinearLayout>
```

`

`     ` `public static class FriendsViewHolder extends RecyclerView.ViewHolder{

```
      ImageView mImageProfile;
      android.widget.TextView mStatus;
      CardView mCardView;
      TranslucentView mName;

      public FriendsViewHolder(View itemView) {
        super(itemView);

        mName = (TranslucentView)itemView. findViewById(R.id.NameUSER);
        WindowManager windowManager = (WindowManager) context
                .getSystemService(Context.WINDOW_SERVICE);
        Display display = windowManager.getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);
        int width = size.x;
        int height = size.y;
        mName.setStartPositions(10, Math.round(height / 2));
      }
```

`

![screenshot_2016-04-12-03-50-12_com rana sahaj myyu 1](https://cloud.githubusercontent.com/assets/16938202/14576433/a0fbbeb0-0386-11e6-830f-b9a32f21005b.png)

**Comment by mallethugo** [comment]
Hi,

Thanks for your comment.
Look my sample and you understand how my library work.

Into my sample I put an ImageView as background in match_parent for width and height. Above this ImageView I put my custom TextView in match_parent too with custom background color (by default this color is white). I draw a transparent text into my custom TextView to see my ImageView background only in letters.

I hope that help you.

**Comment by SahajRana** [comment]
ya thanks... actually i fixed that but the problm came is that the textView is over CardView n when i change back ground of textView,(as text being transparent) it shows the color of cardView. 
Is there any way so that i can put that background behind cardView as transparent  text background

**Comment by mallethugo** [comment]
ok

unfortunately, it musn't view between TranslucentView and the background that you want to show into the transparent text.
